N1 = float(input())
N2 = float(input()) 
soma = "%.2f"%(N1 + N2)
subtracao = "%.2f"% (N1 - N2)
multiplicacao = "%.2f"% (N1 * N2) 
divisao = "%.2f"% (N1 / N2) 
print(soma) 
print(subtracao)
print(multiplicacao)
print(divisao)